# Generated by Django 3.2.3 on 2021-06-01 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='dateCde',
            field=models.DateField(default=datetime.date(2021, 6, 1), null=True),
        ),
    ]
